server:
  port: 8888
spring:
  profiles:
    active: prod
---
server:
  port: 8887
spring:
  profiles: dev
---
server:
  port: 8886
spring:
  profiles: prod

---
#person:
#  lastName: zhangsan
#  age: 20
#  boss: false
#  birth: 2019/06/06
#  maps: {k1: v1, k2: v2}
#  lists:
#    - lisi
#    - wangwu
#  dog:
#    name: 小狗
#    age: 2